### ISSUE TITLE
Upgrade to Keycloak (24 or 25 or) 26

### ISSUE THREAD

**Issue by fengelniederhammer** [loculus-project/loculus#1221]
https://www.keycloak.org/docs/latest/upgrading

And think about whether we want to pin the version to 24 or whether we want to remove the version requirement.
https://github.com/loculus-project/loculus/blob/95628367e0e456b0c0ab21fd1008ce42208019c2/kubernetes/loculus/templates/keycloak-deployment.yaml#L40-L41

- Upgrade Keycloakify 
- Upgrade the Helm Chart
- Look into any migration steps and possibly automate the migration if it isn't too complicated.

**Comment by corneliusroemer** [comment]
There's now Keylcoak 26. Keycloak only officially supports the latest version.

**Comment by fhennig** [comment]
Intermediate findings for upgarding keycloak

- in v24: the `declarative-user-profile` was removed; user profiles are now enabled by default. We just remove the feature flag
- in v25: [hostname](https://www.keycloak.org/docs/26.0.5/upgrading/#new-hostname-options) settings were changed. We can stick with :v1 but it looks like moving to the new config is also easy.

Good point @corneliusroemer about the Keycloakify theme! Apparently the v10 of Keycloakify was almost a complete rewrite ([source](https://docs.keycloakify.dev/faq-and-help/migration-guides/v9-greater-than-v10)) -- Sounds like it could be annoying. But I'll just look into the keycloakify upgrade on its own next.

**Comment by corneliusroemer** [comment]
I'd do keycloakify first, it's the bigger part of the work, we were waiting for the release of V10, we had some discussions on this in the past, see issues and Slack.

**Comment by corneliusroemer** [comment]
> But when just testing v25, I couldn't get it to start, also when switching to the default theme, but it also didn't show any errors.

@fhennig It would be good if you made a PR that shows what you've tried otherwise it's hard to help :)

I got errors that lead me down the path of removing the feature flag and setting hostname-strict to false: https://github.com/loculus-project/loculus/pull/3265/files

When did you not see errors?

**Comment by corneliusroemer** [comment]
I got keycloak 25 to work through some debugging. End result: the health endpoint ports have changed, this is buried in the migration nodes. So kubernetes marks the pod as "not ready" which means that the load balancer doesn't route traffic to it.

However, we can bypass it with some port forwarding which confirms that keycloak is successfully up. So now need to solve the health issue.

What helped me was:
- after failing with keycloak 25 (not realizing that kubernetes was not letting traffic through, also not understanding why I couldn't get to the admin console despite no errors in log) I took a step back
- do one step at a time: get it working with keycloak 23, then 24, when that worked try 25
- by that time I had confidence that I knew how keycloak features are enabled disabled

I would have next tried to do the setup outside of kubernetes to remove that variable, but chatgpt helped me work around it.

**Comment by corneliusroemer** [comment]
In addition to keycloakify, for upgrade from keycloak v25 to v26 we'll need to:
- Use hostname v2: https://www.keycloak.org/docs/latest/upgrading/#hostname-v1-feature-removed
- Replace proxy option: https://www.keycloak.org/docs/latest/upgrading/#proxy-option-removed

But both things are already possible in v25, so can test out on PR #3265.

**Comment by fhennig** [comment]
Hey! Thanks for looking into this

> It would be good if you made a PR that shows what you've tried otherwise it's hard to help :)

I'll push my work next time, good point. But that was more of a status update, I wasn't done looking into it myself. I am slightly surprised that you picked this up all of the sudden!

> We can't actually stick with v1, it's been removed in v26

I know, I just mentioned this as a way to help debugging why v25 isn't working.
