### ISSUE TITLE
Tooltip clipped on review page

### ISSUE THREAD

**Issue by corneliusroemer** [loculus-project/loculus#1447]
Tooltip is clipped on review page, it's possibly not a z-score issue per https://github.com/ReactTooltip/react-tooltip/issues/712 but to do with div nesting, see https://stackoverflow.com/a/50712029/7483211

_Originally posted in https://github.com/loculus-project/loculus/pull/1371#pullrequestreview-1952999865_

See following examples:

<img width="846" alt="image" src="https://github.com/loculus-project/loculus/assets/25161793/c44e1c9b-5d77-4ab4-94a1-16a2a12a533c">

<img width="603" alt="image" src="https://github.com/loculus-project/loculus/assets/25161793/a9c0f77b-69fe-43c1-a6be-d6b739b01a9f">

**Comment by chaoran-chen** [comment]
@fhennig, I'm assigning this to you in case your current work on the review page will anyways solve this. If not, feel free to remove the assignment again.

**Comment by corneliusroemer** [comment]
When fixing this, check whether this also fixes https://github.com/loculus-project/loculus/issues/3198 in one go
