### ISSUE TITLE
Metadata download: timestamps are serialized as unix integer timestamp rather than iso-string

### ISSUE THREAD

**Issue by corneliusroemer** [loculus-project/loculus#1502]
From #1421:

`submittedAt` and `released at` is a unix timestamp, we should serialize it as human readable timestamp, something like `2023-01-05Z23:11:56`?

This requires changes to SILO

**Comment by theosanderson** [comment]
I think the only agreed change we plan to make year has been carried out, as discussed in https://github.com/loculus-project/loculus/issues/838
