### ISSUE TITLE
Review page (and `/get-sequences` endpoint) is slow

### ISSUE THREAD

**Issue by fengelniederhammer** [loculus-project/loculus#1612]
I just noticed that the `/get-sequences` endpoint is slow when there are many sequences in the database:

* Submit 100,000 dummy sequences. 
* Go to the review page
* What I observe (locally and on the current main deployment): The sequences take very long to load, and `https://backend-main.loculus.org/dummy-organism/get-sequences?groupIdsFilter=2&initialStatusesFilter=RECEIVED,IN_PROCESSING,HAS_ERRORS,AWAITING_APPROVAL&statusesFilter=RECEIVED,IN_PROCESSING,HAS_ERRORS,AWAITING_APPROVAL&page=0&size=50` take around 8 seconds to finish.

I added some log statements locally. The method `SubmissionDatabaseService::getSequences` takes the full time. Something in that query must be quite slow.

**Comment by corneliusroemer** [comment]
To distinguish this issue: In contrast to #3269 this is purely about the performance of the backend, not the symptom of the website review page being slow as a result.
