### ISSUE TITLE
Make playwright tests less brittle: replace broad `getByText` 

### ISSUE THREAD

**Issue by corneliusroemer** [loculus-project/loculus#1692]
We should do a broad code search on `getByText` and replace with non-flaky alternatives. Whenever we use broad getByText we're _actually_ testing: this text must only appear once, which is definitely not what we want. We don't want it to fail if submission date and release data happen to be identical etc.

_Originally posted by @corneliusroemer in https://github.com/loculus-project/loculus/issues/1685#issuecomment-2082494066_

**Comment by theosanderson** [comment]
In my opinion this issue could be closed for the reasons that Fabian articulates (though it's definitely important for us to remember the behaviour as Cornelius notes)

**Comment by corneliusroemer** [comment]
Fair, maybe we could have a list of gotchas somewhere in dev docs where we could add this? Just to avoid having to rediscover the wheel. Or maybe the issue is enough.
