### ISSUE TITLE
Feature: Substring search for string fields on browse page

### ISSUE THREAD

**Issue by corneliusroemer** [loculus-project/loculus#1742]
For fields like Authors, it would be great to have the ability to do a substring search, e.g. put in `Rambaut` and you get all the sequences that contain the string `Rambaut`.

This is currently not (yet) supported by LAPIS: see https://github.com/GenSpectrum/LAPIS/issues/750

Substring search will be useful for at least the following metadata types:
- Authors
- Sequence/Isolate names
- Group name
- Author affiliation

An interesting question for the search field will be how to integrate substring search with the "autoComplete" feature. Would we show substring matches as an additional type of autocomplete with a number next to it showing matches? This is (without the numbers) what INSDC do: it'll show you exact matches but do substring search nonetheless.

@theosanderson mentioned substring search a few days ago: https://loculus.slack.com/archives/C05G172HL6L/p1713873204853119

**Comment by chaoran-chen** [comment]
Is there anything missing for this issue or can we close it? (ping @corneliusroemer, @theosanderson, @anna-parker, @fengelniederhammer)

**Comment by corneliusroemer** [comment]
It depends why you want to close it.

We can close if we make new issues 😄 

- [ ] We haven't added it to all the fields where it would make sense to add it per my list in the issue
- [ ] We might want to make all of the following possible through checkbox (rather than triplicating fields):
  - autosuggest (exact)
  - substring
  - regex

**Comment by chaoran-chen** [comment]
The first one is a Pathoplexus and the second one is a Loculus issue, right?

**Comment by chaoran-chen** [comment]
I created two new issues:

- #2681
- https://github.com/pathoplexus/pathoplexus/issues/79

**Comment by corneliusroemer** [comment]
The first one is a Pathoplexus issue but it's also a Loculus issue as we have basically the same fields in loculus. I'll make a new issue for that here.
