### ISSUE TITLE
React hydration errors

### ISSUE THREAD

**Issue by chaoran-chen** [loculus-project/loculus#1755]
When opening the browse page, I see a few warnings in the browser console:

![image](https://github.com/loculus-project/loculus/assets/18666552/3ac5ab73-26bb-4e28-8cdc-64ce1ee456a0)

The links are:

- https://react.dev/errors/425?invariant=425
- https://react.dev/errors/418?invariant=418
- https://react.dev/errors/423?invariant=423

**Comment by theosanderson** [comment]
This has likely been fixed for a long time since #2112
