### ISSUE TITLE
Possible group creation race condition: two ingest pipelines starting up

### ISSUE THREAD

**Issue by corneliusroemer** [loculus-project/loculus#1794]
When we have two ingest pipelines starting on a clean database, there's a very small chance of a race condition where both pipelines create an insdc_ingest_group

Rather than implementing locking which is unnecessary, could we just pre-populate the insdc_ingest_group as a service-group, similar to service account?

In production this will unlikely cause issues as the race condition is so unlikely (say 1 in 10000) and we will only create the group once in the entire app lifetime. But for preview deployments it would be nice, it would also simplify ingest code as we wouldn't have to create/query the group but could use a known id (passed through config say).

**Comment by chaoran-chen** [comment]
@corneliusroemer, @anna-parker, this has been already resolved a while ago, right?
