### ISSUE TITLE
React hydration error after group creation during E2E on webkit

### ISSUE THREAD

**Issue by corneliusroemer** [loculus-project/loculus#1837]
On my crusade to deflake tests, I've noticed that there seems to be a stochastic issue with react hydration after clicking the group creation button.

Running tests locally, the error occurs only on webkit.

Might be due to some race condition.

```
[astro-island] Error hydrating /_astro/GroupCreationForm.BjSHbmEE.js TypeError: Importing a module script failed.
```

Note that the request made looks correct. Further details are in logs maybe

<img width="1279" alt="Chromium 2024-05-09 23 36 20" src="https://github.com/loculus-project/loculus/assets/25161793/2967a814-1f1b-48c8-a13b-696a52f18ec9">

**Comment by theosanderson** [comment]
Can we close this since we maybe haven't come across it for a while?
