### ISSUE TITLE
Reorder postgres tables moving long columns to end of table for better debugging

### ISSUE THREAD

**Issue by corneliusroemer** [loculus-project/loculus#1921]
I'm currently debugging a confusing state of loculus and looking at database tables.

Something that would make debugging more pleasant is if long columns were at the right hand side of columns, so one can see all short columns on one screen.

This is the current situation:

<img width="1658" alt="Hyper 2024-05-15 16 55 14" src="https://github.com/loculus-project/loculus/assets/25161793/9ddf401d-8059-43bc-bbd6-754d364aca77">

It would be nice if I didn't have to scroll right for ages to see the rest:

<img width="1270" alt="image" src="https://github.com/loculus-project/loculus/assets/25161793/af0a497b-f2ad-44d6-9954-49cb25118098">

This might be as easy as reordering the schema?

I know I can do the following but still, would be nice if one could `select * from sequence_entries;` etc

```sql
select s.accession, s.version, s.pipeline_version, s.errors, s.warnings, s.processing_status, s.started_processing_at, s.finished_processing_at   from sequence_entries_preprocessed_data as s LIMIT 2;
```

**Comment by corneliusroemer** [comment]
Just coming across this again when trying to debug, it is harmful that the json column is in the middle. We should really see whether we can move it to the end somehow. This could involve a view for example, we don't have to alter the actual table necessarily.

> One other idea occurs to me: you can define a VIEW that specifies the order of columns how you like it, without changing the physical position of the column in the base table.

**Comment by chaoran-chen** [comment]
Why don't you just write a corresponding query when you look at the data? The returned results are in the order of their mentons in the select clause.

**Comment by corneliusroemer** [comment]
Too tedious to do every time

**Comment by chaoran-chen** [comment]
I don't think that it is a good idea to add views for purely debugging purposes for a production system. What about having a few SQL scripts that you can call? We can add a folder somewhere with a collection of useful scripts.

**Comment by chaoran-chen** [comment]
I also recommend using a GUI to look up database tables. In DataGrip, it is easy to change the order of columns simply by drag-and-dropping the column headers.

**Comment by chaoran-chen** [comment]
I'll close this again as the original suggestion to "Reorder postgres tables" is not really possible since we started database schema versioning (at least not without recreating and copying all data).
