### ISSUE TITLE
How to download individual metadata?

### ISSUE THREAD

**Issue by emmahodcroft** [loculus-project/loculus#2019]
I was tying to check our field (column) names and so went to download the info for just one sequence. I went to Ebola Sudan (though don't think this matters) and clicked on the first sequence in the list, bringing it into the 'pop up view'.

However, I was surprised when I clicked the 'download' icon in the top-right and was not given any choice of _what_ to download - it just downloaded a Fasta - when what I actually want is the metadata!

I'd suggest we add possibly two links (one FASTA, one metadata) or some other kind of selector (perhaps also offering GB file that has both?) - it's odd to me one can't just download metadata for one sequence!

**Comment by fhennig** [comment]
@emmahodcroft what to you mean with GB file? 

I'd suggest that when the download button is clicked there is a dropdown/pop-up menu with multiple options (_metadata_, _Fasta_, GB (?))

**Comment by theosanderson** [comment]
I guess Emma means a GenBank file. I would defer that to a future issue for now as it will be quite a bit more involved.

**Comment by fhennig** [comment]
In the full sequence view (i.e. https://pathoplexus.org/seq/PP_000PHAJ.2 ) the _Download FASTA_ button is not rendered if the sequence is restricted. Should downloading metadata still be allowed or not? For now (because it's the easiest) I just have it display nothing if the sequence is restricted, and show both options if it isn't.

**Comment by fhennig** [comment]
Can you give me a bit of domain knowledge about this, what does it mean that a sequence is restricted?

**Comment by theosanderson** [comment]
The best nomenclature is probably a bit more nuanced than calling the sequence just "restricted" - although it's easy to slip into doing that. All sequences released on Pathoplexus are publicly available. But some researchers want to maintain an exclusive ability to publish results analysing their sequences for some time to ensure they are not "scooped". To allow early sharing of sequences Pathoplexus allows submitters to choose between "Open" and "Restricted" data use terms on submission. The "Restricted" case, if chosen, applies for up to a year, then sequences move to the Open Data Use Terms. Under the Restricted Data Use Terms the sequence is available, but only under the [Restricted Use Terms](https://pathoplexus.org/about/terms-of-use/restricted-data) which prevent others from publishing analysis focusing on this data.

From a dev point of view the goals are to make very clear when sequences are only available under restricted terms, but not to prevent their download.

**Comment by fhennig** [comment]
Got it, thanks for clarifying!

**Comment by theosanderson** [comment]
(For others reading - as discussed in the more detailed review - on reviewing the code this visibility-of-download-button thing isn't about restricted sequences but about revocations)
