### ISSUE TITLE
Ingest reorders authors alphabetically, it probably shouldn't

### ISSUE THREAD

**Issue by corneliusroemer** [loculus-project/loculus#2198]
Ingest currently seems to order authors alphabetically
<img width="985" alt="Brave Browser 2024-06-29 14 28 11" src="https://github.com/loculus-project/loculus/assets/25161793/f59d0814-c0b2-4a69-a880-4be263c3cea1">

Previous versions didn't order alphabetically, which is I think what we shouldn't do (just keep authors in the order they come from NCBI):
<img width="985" alt="Brave Browser 2024-06-29 14 28 11" src="https://github.com/loculus-project/loculus/assets/25161793/6ab8f89b-9549-4b48-ba36-34d66a7dfe54">
<img width="820" alt="Brave Browser 2024-06-29 14 28 14" src="https://github.com/loculus-project/loculus/assets/25161793/196e8db2-f15d-4529-b33a-e64c6a66e712">

**Comment by chaoran-chen** [comment]
Closing this in favor of #2650.
