### ISSUE TITLE
ENA submission

### ISSUE THREAD

**Issue by anna-parker** [loculus-project/loculus#2264]
## MVP tasks:
- [x] : Create a backend endpoint
- [x] : Get a clear overview of all the upload commands
- [x] : Do one test with the broker account on production prior to real thing - we can get ENA to delete 1 test submission

## Submission steps:
- [x] 0. : Create a pod with permissions to call loculus for submission data, group data and post external (ena - related) submission results (e.g. insdc_accession). It should have a main submission table to store submission status, as well as project + sample + assembly submission table for each individual stage.
- [x] a. should have ena submission privileges. 
- [x] b. add flyway to ena pod and have tables initialized by flyway to track versions
- [x] 1. : Get a list of sequences that are approved for release and should be submitted to ENA (i.e. have not started submission process=not in submission table and are not from INSDC).
- [x] a. Send slack notification
- [x] #2403
 a. Add sequences to main submission table. This should trigger the submission process
- [x] #2397
a. Get group info from loculus
b. check if project exists for (group, organism) already
c. if not add details to table: create xml with project details, start submission, keep progress in table, then add results in table. 
d. Make sure when project submission finished project_submission is marked as complete in main submission table. 
- [x] #2398
a. When project submission is finished, add accession to sample table with status ready for sample submission
b. Create submission xml
c. start submission, keep status of submission in table, then add results to table when finished.  
d. Make sure when sample submission finished sample_submission is marked as complete in main submission table. 
- [x] #2399
a. When sample submission is finished, add accession to analysis table with status ready for assembly submission
b. create submission xml
c. start submission, keep status of submission in table, then add results to table when finished. 
d. Make sure when assembly submission finished assembly_submission is marked as complete in main submission table. 
- [x] #2424
- [x] https://github.com/loculus-project/loculus/issues/2832
- [x] #2425

**Comment by anna-parker** [comment]
This is done!!!

**Comment by corneliusroemer** [comment]
Done but there are still quite a few improvements we can still make :)
