### ISSUE TITLE
Initial processing gives wrong number of sequences for large file?

### ISSUE THREAD

**Issue by emmahodcroft** [loculus-project/loculus#2559]
Testing out our current Ebola Zaire sample file, which is 3855 sequences large, when it first starts to load on the processing page, it shows 3955 instead.

This is only for a couple of seconds then it corrects to 3855, but it's weird.

![image](https://github.com/user-attachments/assets/a4a7cc28-f9ea-43d3-85e4-2f8c91a22b64)

A few minutes later:
![image](https://github.com/user-attachments/assets/3a77b860-9347-4122-acc3-20ed82d2d15a)

**Comment by chaoran-chen** [comment]
Ah, I created a duplicate in #3095! I'll close this one because the new one contains a video ;)

**Comment by corneliusroemer** [comment]
I actually find the images clearer 😀
