### ISSUE TITLE
Add Regex/partial-string search to more fields

### ISSUE THREAD

**Issue by emmahodcroft** [loculus-project/loculus#2576]
Currently (I understand) only `authors` has partial-match string search. It would be great to expand this to other fields.

Off the top of my head (but please others comment to recommend more):
- submissionID
- authorAffiliations
- specimenCollectorSampleId

**Comment by chaoran-chen** [comment]
I created a corresponding task for Pathoplexus: https://github.com/pathoplexus/pathoplexus/issues/79
