### ISSUE TITLE
Revisions from Curators to INSDC-Ingest-Group Are Auto-approved

### ISSUE THREAD

**Issue by emmahodcroft** [loculus-project/loculus#2613]
Ideally, when curating sequences from INSDC, we would like 1 curator to set up the revision, and another (different) to approve it and 'submit' it to become live.

However, at the moment, all sequences in 'Review' are auto-approved for INSDC-ingest-group. So, one reviewer sets this up, and it's auto-approved without having a chance for another reviewer to approve.

One possible fix would be to only auto-approve 'version 1' (`.1`) sequences, and anything higher than this (e.g. a revision) needs to be approved by a curator. 

This would be fairly high-priority post-launch as we have our 'four eyes' principle written into our docs (and it's probably a good idea)

(As a follow up - re-edit docs after fixing this issue
- Curator SOP
- Data submission & processing)

**Comment by chaoran-chen** [comment]
Closing this in favor of the duplicated issue #3087.
