### ISSUE TITLE
South Sudan missing in accepted countries due to missing from ENA checklist

### ISSUE THREAD

**Issue by corneliusroemer** [loculus-project/loculus#2636]
Loculus' default list of accepted countries misses South Sudan (independent since 2011) and possibly some more recently independent countries.

We use the ENA checklist https://www.ebi.ac.uk/ena/browser/view/ERC000011 - so that list might have to be updates as well.

South Sudan _is_ in the official INSDC country list, it's just missing from _that_ checklist.

https://www.ncbi.nlm.nih.gov/genbank/collab/country/

We might also want to add historical countries (in case they haven't been added) - as it is customary to describe geolocations by the names at the time of collection, at least during modern times.

**Comment by anna-parker** [comment]
I did not enforced the accepted countries list for samples from INSDC so I don't think that this is high priority.

**Comment by chaoran-chen** [comment]
Current question: We don't know whether ENA will accept sequences with "South Sudan" as country. We will test it.
