### ISSUE TITLE
Dynamics resizing of pages with collapsible content 

### ISSUE THREAD

**Issue by emmahodcroft** [loculus-project/loculus#2662]
On pages with a lot of collapsible content (in particular, Pathoplexus FAQ), the page resizes from when all is collapsed and then when 1 or more things are expanded. This provides a bit of a weird user experience as the page moves around a bit.

While collapsed:
![image](https://github.com/user-attachments/assets/4da59899-3ee3-42cf-9818-74c976e3c00a)

Expanded:
![image](https://github.com/user-attachments/assets/0d123e48-52ea-4a4a-b8ce-840b34dcb61d)

(Subtle difference but page 'jumps' when you do it - try it out [here](https://pathoplexus.org/about/faq))

Would be nice (but not urgent) to have page size anticipate the expanded size somehow so the page stays the same ratios. 

This could also be being exacerbated by 'long' menu items like 'Frequently Asked Questions (FAQ)' and 'Open Data Terms of Use (Summary)' that wrap and unwrap with this resizing.

**Comment by corneliusroemer** [comment]
Screencast (@emmahodcroft can you confirm this is what you meant by the bug)?

![2024-09-03 12 22 35](https://github.com/user-attachments/assets/95fe8fb7-0917-48b3-a15e-b26228b2f468)
