### ISSUE TITLE
It should be possible to run Loculus without `dateToSortBy`

### ISSUE THREAD

**Issue by theosanderson** [loculus-project/loculus#2668]
We established today that we when we no longer set `dateToSortBy` in Loculus values, the LAPIS instances crash. The intended behaviour is that it is possible to run Silo without this (and maybe it is, with the right configuration) and we would like it to be possible to deploy Loculus with no date fields. We should investigate what the problem was and either raise a bug in Silo or adjust Loculus configuration.

**Comment by Taepper** [comment]
How prioritized is this? I guess understanding our setup more thoroughly would be good, as there are definitely tests in LAPIS and SILO that work without that flag.

Could you remind me again on what exactly was crashing? I seem to recall that the LAPIS pod failed to come up?

**Comment by theosanderson** [comment]
I'm investigating this in #2706. Atm it seems like at least SILO - it may just have been the exact way that we adjusted the config that resulted in a missing key for the deployment. I will continue to investigate

**Comment by corneliusroemer** [comment]
What about LAPIS though, will it be happy with this removed? We should remove the config and then see what happens.
