### ISSUE TITLE
Add substring search for more fields

### ISSUE THREAD

**Issue by corneliusroemer** [loculus-project/loculus#2684]
_This was posted by Chaoran as Pathoplexus issue, but we should make the same changes here in the default config. I'd start upstream (i.e. Loculus, then apply downstream, but either direction works)_

https://github.com/pathoplexus/pathoplexus/issues/79

@emmahodcroft wrote in https://github.com/loculus-project/loculus/issues/2576#issue-2486920360:

Currently (I understand) only `authors` has partial-match string search. It would be great to expand this to other fields.

Off the top of my head (but please others comment to recommend more):
- submissionID
- authorAffiliations
- specimenCollectorSampleId

@corneliusroemer wrote in https://github.com/loculus-project/loculus/issues/1742#issue-2275572466:

Substring search will be useful for at least the following metadata types:
- Authors
- Sequence/Isolate names
- ~Group name~
- Author affiliation

**Comment by chaoran-chen** [comment]
huh? I think we were addding labels at the same time

**Comment by chaoran-chen** [comment]
and I wanted to add the same but somehow ended up deleting them?

**Comment by theosanderson** [comment]
To confirm, this isn't purely a config change, it needs some Typescript

**Comment by corneliusroemer** [comment]
This PR should be helpful as a template for the types of files and changes necessary: https://github.com/loculus-project/loculus/pull/2491/files

**Comment by fhennig** [comment]
the author affiliations doesn't support free-text entry at the moment. should this be changed then? Currently it's a dropdown menu.

**Comment by emmahodcroft** [comment]
Hm, I think it now supports free-text entry, which is probably good!
