### ISSUE TITLE
Have an explicit sequence length cut-off in preprocessing

### ISSUE THREAD

**Issue by anna-parker** [loculus-project/loculus#2722]
We use nextclade for alignment which has a minimum sequence length (the default is 100bp). We should check if this is the best choice and potentially change our preprocessing configs to reflect this.

**Comment by anna-parker** [comment]
I see Theo has already opened an issue for this - sorry! https://github.com/loculus-project/loculus/issues/2721

**Comment by corneliusroemer** [comment]
We possibly want a different cutoff for ingest and for non-ingest sequences

If we lower the cutoff for user submissions, we may want to have to configure and extra filter in ingest.

**Comment by corneliusroemer** [comment]
Then close as "not planned" = gray not as completed ;)
