### ISSUE TITLE
Add backend endpoint to get number of sequences per pathogen similar to get-released-data

### ISSUE THREAD

**Issue by corneliusroemer** [loculus-project/loculus#2727]
It can happen that the backend aborts sending results when requested from get-released-data and this isn't easily noticed by clients.

One idea is to provide a new endpoint that quickly returns the total number of sequences expected by get-released-data - to allow clients to decide.

Alternative is to have backend calculate a full checksum, slightly more robust than just counting sequences but more work.

We might also just want to modify the backend to save get-released-data output to file before sending it to client once database->backend was successful.

**Comment by fengelniederhammer** [comment]
Let's rather do this? https://github.com/loculus-project/loculus/issues/2724#issuecomment-2337258697

In general this seems to be a duplicate of #2724

**Comment by corneliusroemer** [comment]
Wasn't aware of #2724, thanks @fengelniederhammer
