### ISSUE TITLE
Switch to using `pnpm` instead of npm for website: much faster and space efficient

### ISSUE THREAD

**Issue by corneliusroemer** [loculus-project/loculus#2754]
Pnpm is a faster and space efficient replacement of npm. It's basically drop in. And it's massively sped up my bisection of npm packages.

**Comment by theosanderson** [comment]
(It's great that you used it to such great effect, but this wouldn't be blocking for that)

**Comment by corneliusroemer** [comment]
It's one command to install pnpm if you haven't got it admins it'd save quite a bit of dev and CI time overall but I agree it's not a big deal
