### ISSUE TITLE
Compress compressed sequences in backend with zstd dictionary

### ISSUE THREAD

**Issue by corneliusroemer** [loculus-project/loculus#2790]
I have a hunch that we don't use zstd dictionaries for compression of sequences. Using dictionaries will likely enhance compression efficiency by an order of magnitude which is essential for scalability and general resource efficiency.

One can start off using simply the refseq as the dictionary, though it'd be better to use a diverse subset of sequences for the best compression ratios.

If using more custom dictionaries, one would want to store the dictionaries used in a separate table. For now using the ref seqs seems like the best tradeoff for simplicity and efficiency.

**Comment by theosanderson** [comment]
I had understood that we did or haf intended to, but that may be a misunderstanding

**Comment by corneliusroemer** [comment]
It might actually be not worth (at least for a start) to use different dictionaries for different segments/organisms. One could potentially start off ny constructing _one_ dictionary that contains all ref seqs and segments. This might start becoming inefficient above a certain ref seqs size but it's definitely the easiest to get going with.

The trickiest part is that one needs to migrate the db for every dictionary change.

**Comment by theosanderson** [comment]
We use dictionaries – unless there's a bug https://github.com/loculus-project/loculus/blob/9a76840143ad41034eedbbee3474f8ac373af02d/backend/src/main/kotlin/org/loculus/backend/service/submission/CompressionService.kt#L4

**Comment by corneliusroemer** [comment]
Ah nice! That's cool, wasn't aware! 

I think we could use a higher compression level though: https://github.com/loculus-project/loculus/blob/9a76840143ad41034eedbbee3474f8ac373af02d/backend%2Fsrc%2Fmain%2Fkotlin%2Forg%2Floculus%2Fbackend%2Fservice%2Fsubmission%2FCompressionService.kt#L144-L146

We use 3 which is fairly low given we only need to compress once, and will keep it around in db forever.

Using a dictionary with more diverse sequences instead of just ref might help a little but would be a pain to config/maintain so definitely not worth it for now.

We should look into compression level though.
