### ISSUE TITLE
deploy.py does not always correctly substitute external content referenced by URL when running locally

### ISSUE THREAD

**Issue by anna-parker** [loculus-project/loculus#2806]
This has happened to me maybe ~3 times when running locally. I will start all pods and then I get this error from prepro when I try to submit sequences:
```
DEBUG:urllib3.connectionpool:http://127.0.0.1:8079 "POST /cchf/submit-processed-data?pipelineVersion=1 HTTP/1.1" 422 None
ERROR:root:Submitting processed data failed. Traceback : Submitting processed data failed. Status code: 422
Response: {"type":"about:blank","title":"Unprocessable Entity","status":422,"detail":"The length of 'S' in 'alignedNucleotideSequences' is 1672, but it should be 100.","instance":"/cchf/submit-processed-data"}
```
Prepro cannot submit sequences to the backend because the backend expects sequences of length 100 (this is the length of the reference URL link - so this means that the URL has not been replaced with the actual contents), 
```
len("[[URL:https://raw.githubusercontent.com/corneliusroemer/seqs/main/artefacts/cchf/reference_S.fasta]]")
``` 

In this specific case I updated all templates except for the database - so potentially this is an update issue?

**Comment by anna-parker** [comment]
I think I figured it out, running
```
../deploy.py cluster --dev
../deploy.py helm --dev
```
and then using the resulting config for running the backend leads to an error.
In order to run the backend one must additionally run
```
../generate_local_test_config.sh
```
to actually replace the URLs with their contents.

**Comment by corneliusroemer** [comment]
Can you clarify how you run the backend? `./start_dev.sh`?

Maybe we have to update our local dev docs.

**Comment by theosanderson** [comment]
I'm not sure this is a bug, except potentially in the docs if they are confusing or don't capture this. `deploy.py helm` should not rewrite config files.

**Comment by theosanderson** [comment]
(deploy.py has a `config` command for that, which is what the generate_local script uses)

**Comment by theosanderson** [comment]
One could use a real temporary directory in `/tmp`

**Comment by anna-parker** [comment]
Thanks for the comments - I updated the deploy script to make this a bit clearer for other users.
