### ISSUE TITLE
Investigate how group name ends up in released data

### ISSUE THREAD

**Issue by corneliusroemer** [loculus-project/loculus#2815]
@anna-parker and I were trying to figure out where the "groupName" field in `/get-released-data` comes from. It doesn't seem to be joined on in the database at all.

My hunch is that the name gets passed to preprocessing? But that's odd because group name should eventually be changeable (see https://github.com/loculus-project/loculus/issues/2258)

**Comment by fengelniederhammer** [comment]
That's probably it?
https://github.com/loculus-project/loculus/blob/cca00bbc9174e3080e7507802ce838f186babc22/backend/src/main/kotlin/org/loculus/backend/model/ReleasedDataModel.kt#L67

**Comment by corneliusroemer** [comment]
@chaoran-chen closed as completed not not planned if @fengelniederhammer's has correctly investigated :)

**Comment by chaoran-chen** [comment]
Yes right, mission / investigation fulfilled! 💪

**Comment by corneliusroemer** [comment]
Just for posterity, this confirms that the group name is output of preprocessing - so any changes are not reflected until we reprocess - probably not great once we start allowing editing of group names.

We might want to change how we do this. I'll make an issue.

**Comment by chaoran-chen** [comment]
See https://github.com/loculus-project/loculus/issues/2819#issuecomment-2356925675 for my response.
