### ISSUE TITLE
Preferentially use insdc_ingest_group's id instead of group name (which isn't unique)

### ISSUE THREAD

**Issue by corneliusroemer** [loculus-project/loculus#2820]
In ingest, we currently seem to use the particular group name rather than id to determine whether a submission was from insdc ingest or not.

As group name's are not unique, we should not use them (at least in production). We should preferentially use the group id - and make that configurable (through config) for production settings.

**Comment by anna-parker** [comment]
As mentioned via chat - for previews we might still want to use the name as the ID is related to the order the groups were made in, but for production switching to the ID makes a lot of sense :-)

**Comment by theosanderson** [comment]
There's something that seems a bit messy about that mixture (though I understand the rationale).

As an alternative, when retrieving the data for the pipeline the backend could annotate it with `is_ingest` (or something) if it belongs to a group of which `insdc_ingest_user` is a member

**Comment by chaoran-chen** [comment]
> In ingest, we currently seem to use the particular group name rather than id to determine whether a submission was from insdc ingest or not.

Sorry, I don't understand: is there maybe a typo? Do you mean that tge ENA submission/deposit uses the group name of the INSDC ingest group? Or that the preprocessing pipeline uses it? (I assume that the ingest can find out its own group ID and use it?)

**Comment by corneliusroemer** [comment]
Ah indeed I think there might be a typo. Anya and I remembered that we seemed to use group name somewhere but we might have both gotten confused. Maybe in prepro instead of ingest.

**Comment by corneliusroemer** [comment]
So we definitely use the _username_ on prepro: https://github.com/loculus-project/loculus/blob/1584907beef4de3c89bc0cc67e77a7a3014baddf/preprocessing/nextclade/src/loculus_preprocessing/prepro.py#L643 but that's fine, user name is unique.

**Comment by corneliusroemer** [comment]
I think I got lead astray by my imagination after misunderstanding #2819

I couldn't find us using the insdc_ingest_group used anywhere. Not in ingest, not in prepro is it used afaict. So closing this as unplanned - always good to not have to do stuff!
