### ISSUE TITLE
Ingest: get nucleotide accessions to ignore from extended metadata table

### ISSUE THREAD

**Issue by corneliusroemer** [loculus-project/loculus#2832]
We need to find out the nucleotide accessions that correspond to ENA deposited sequences so ingest can ignore these (otherwise we end up with infinite loop).

This might require some changes to ena submission so we find out the nucleotide accessions from the GCA assembly accessions.

For reference:

<img width="1030" alt="image" src="https://github.com/user-attachments/assets/7e49d6c8-5a60-40d7-a766-43b310e0e284">

<img width="1030" alt="Brave Browser 2024-09-18 14 40 44" src="https://github.com/user-attachments/assets/18e96c10-aa9f-433e-8170-9176b1116b12">

@anna-parker (this is a test)

**Comment by theosanderson** [comment]
We plan to annotate our ENA depositions with PP metadata right (the PP accession, as some cross-reference?) Can't we use that?

**Comment by corneliusroemer** [comment]
It probably doesn't end up in NCBI virus export so can't do that easily afaict

@anna-parker

**Comment by theosanderson** [comment]
Hmm does this mean we could be failing to ingest some other quite important data? (Not a criticism - just for understanding: I guess I previously thought we were capturing 100% of data)
