### ISSUE TITLE
submission page freezes when too many sequences waiting for approval

### ISSUE THREAD

**Issue by anna-parker** [loculus-project/loculus#2880]
As a curator when I log in to submit I am first logged in in the INSDC ingest user group, the page freezes before it loads, probably because there are so many sequences: 
<img width="656" alt="image" src="https://github.com/user-attachments/assets/dff3da7e-9f7f-43f1-9279-ecbc1dd7873e">

**Comment by chaoran-chen** [comment]
I guess (not verified, just from memory) the problem is that the page is calling the `get-sequences` endpoint which returns the number of sequences per status but also information about every sequence which is quite big.
