### ISSUE TITLE
Website crashes with OOM when reviewing west nile as ingest user due to 16k errored sequences

### ISSUE THREAD

**Issue by anna-parker** [loculus-project/loculus#2881]
Clicking on the west nile page submission page as a curator a couple times takes down the webpage
![image](https://github.com/user-attachments/assets/88bcd903-c501-4dbb-8d31-84dff5a3999a)

**Comment by corneliusroemer** [comment]
<img width="1725" alt="iTerm2 2024-09-26 16 35 17" src="https://github.com/user-attachments/assets/9d2b6a9f-85f3-40cb-aee1-41905bb072e9">

**Comment by theosanderson** [comment]
Closing in favour of https://github.com/loculus-project/loculus/issues/3031 if that's OK (with this issue still useful to capture the detail)
