### ISSUE TITLE
Loculus documentation (loculus.org) is not indexed well by google

### ISSUE THREAD

**Issue by corneliusroemer** [loculus-project/loculus#2940]
Search for "system overview loculus ena github loculus.org" on [google](https://www.google.com/search?q=system+overview+loculus+ena+github+loculus.org&sca_esv=85604b0bcae66a71&sxsrf=ADLYWILD79kjBrkIJ3w9BhDpUNAqNrfEuQ%3A1727945534129&ei=Plv-ZqO9B6Lk7_UPvtLMuQ8&ved=0ahUKEwij1ILe6vGIAxUi8rsIHT4pM_cQ4dUDCA8&uact=5&oq=system+overview+loculus+ena+github+loculus.org&gs_lp=Egxnd3Mtd2l6LXNlcnAiLnN5c3RlbSBvdmVydmlldyBsb2N1bHVzIGVuYSBnaXRodWIgbG9jdWx1cy5vcmdI1g5QkwJY5Q1wAngAkAEAmAGJAaABuQ2qAQQxLjE0uAEDyAEA-AEBmAIDoAL2AsICCBAAGIAEGKIEmAMAiAYBkgcDMC4zoAfLFw&sclient=gws-wiz-serp)

It doesn't show obvious docs hits https://loculus.org/introduction/system-overview/#_top

<img width="1559" alt="Brave Browser 2024-10-03 10 52 54" src="https://github.com/user-attachments/assets/ba9c61d0-9136-4901-b596-078261b5bb27">

<img width="1614" alt="Brave Browser 2024-10-03 10 52 59" src="https://github.com/user-attachments/assets/28e95554-a1be-426a-84fc-f2cb63b7e1b1">

**Comment by theosanderson** [comment]
Because the word ENA does not appear on that page?

**Comment by corneliusroemer** [comment]
Yeah I think you're right, we don't have high reputation so it looks for exact matches only. Thanks!

<img width="1226" alt="Brave Browser 2024-10-03 11 01 24" src="https://github.com/user-attachments/assets/e617d9d1-7cab-4ed2-8db8-ae101c451630">
