### ISSUE TITLE
LAPIS readiness probe should return ready even on empty database

### ISSUE THREAD

**Issue by corneliusroemer** [loculus-project/loculus#2941]
It seems that the LAPIS readiness probe fails if the database is empty. We should use a readiness probe that works for an empty database.

Maybe #2934 can help here? @fengelniederhammer 

<img width="1919" alt="image" src="https://github.com/user-attachments/assets/cd7a3cba-3bfe-4cbb-91c2-dc712d04d8be">

**Comment by theosanderson** [comment]
Are you sure? I thought we addressed that. We have lots of instances that show 0 results.

**Comment by corneliusroemer** [comment]
Hmm, it's possible I'm wrong here - I had definitely forgotten to start the backend, so that might have contributed, though it's odd that LAPIS showed not ready in that case instead of SILO preprocessing.

All I know is that LAPIS was showing not ready for a long time in k9s, while the backend was not up. Let's see.
