### ISSUE TITLE
Newly added template playwright tests are failing for webkit

### ISSUE THREAD

**Issue by corneliusroemer** [loculus-project/loculus#2963]
```
2 failed
    [webkit] › pages/submission/template.spec.ts:6:5 › The submit page › should download the metadata file template for submission 
    [webkit] › pages/submission/template.spec.ts:17:5 › The submit page › should download the metadata file template for revision 
```

Added in this PR: https://github.com/loculus-project/loculus/pull/2916

@fengelniederhammer - can you have a look at why webkit fails the newly added tests? In PR CI we only run on chromium which is why this will have escaped us. You can make a new PR and add webkit there to debug.

Should we disable the test for now so we don't have failing CI on main?

**Comment by theosanderson** [comment]
Here is the approach we took last time - skipping the test for WebKit: https://github.com/loculus-project/loculus/blob/006c1818bb1bdfcdf90bc1d74d17c1a2cee6d35b/website/tests/pages/search/index.spec.ts#L136 which IMO is totally reasonable to use here

**Comment by fengelniederhammer** [comment]
Is it a known issue that downloads don't work in webkit? 

It seems to ignore the content disposition header...

**Comment by theosanderson** [comment]
🤷
