### ISSUE TITLE
Improve project deposition mapping/structure

### ISSUE THREAD

**Issue by corneliusroemer** [loculus-project/loculus#2977]
Some ideas for improving the project submissions are in this thread: https://loculus.slack.com/archives/C0757PTR607/p1728464162216809

Currently we show like this:
![image](https://github.com/user-attachments/assets/98bedfd2-285c-45ab-93fb-9cbd23d4d472)

We could try to get something more like this:
<img width="981" alt="image" src="https://github.com/user-attachments/assets/ffea7704-904e-4492-beb1-3cbfb746b399">

Showing like this in NCBI: 
![image](https://github.com/user-attachments/assets/bf058398-b41f-48cf-be35-fe55940023b3)
Corresponding ENA project: https://www.ebi.ac.uk/ena/browser/view/PRJEB80643

The first sample we submitted was incorrectly labelled as genomic DNA - this has been fixed by submitting an EMBL file.

**Comment by anna-parker** [comment]
Interestingly the title that I set is not shown as the title but a subtitle.

**Comment by corneliusroemer** [comment]
I wonder what the best info to include is. We could mention the country and possibly city/state of the submitter - as that is often a good proxy to where sequences are from - even if not 100% accurate.

So we could do:
```
Name: West Nile Virus Genome Sequencing
Title: West Nile Virus genome submissions by Institution Name, City, Country to Pathoplexus
Description: Automated upload of West Nile Virus sequences originally submitted by Institution Name, City, Country to Pathoplexus
```

Then we have a little bit more info on each level. Would be nice if we had a nice group display name, something like "Grubaugh Lab" in addition to the institution which is not as concrete as it could be. For now, given we don't have this, no point in adding, but we could do this in the future.
