### ISSUE TITLE
Have metadata field descriptions in config not in a separate docs

### ISSUE THREAD

**Issue by anna-parker** [loculus-project/loculus#3013]
Currently metadata fields are defined in the `values.yaml`: https://github.com/loculus-project/loculus/blob/main/kubernetes/loculus/values.yaml#L57 (overwritten by https://github.com/pathoplexus/pathoplexus/blob/main/loculus_values/values.yaml#L73) but are described in the docs: https://github.com/pathoplexus/pathoplexus/blob/main/monorepo/website/src/pages/docs/concepts/metadataformat.mdx. This means any change in fields needs to be made in two locations. It is also hard to review. 

Instead we should add descriptions to the `values.yaml` AND generate the docs from the `values.yaml` AND let users download metadata with decriptions. 

Additionally, we currently use the same metadata fields for all organisms but in future this might not be the case. 

Suggestion: create a markdown component for the metadata tables in the docs similarly to how Theo added additional markdown formatting in https://github.com/loculus-project/loculus/pull/1931, see `loculus/website/src/styles/mdcontainer.scss`

**Comment by corneliusroemer** [comment]
I don't think we use loculus values.yaml in pathoplexus, pathoplexus defines its own values.yaml - so yeah there's duplication but I'm not quite sure what you're suggesting should be done.

**Comment by corneliusroemer** [comment]
Closing this issue for now in favor of https://github.com/pathoplexus/pathoplexus/issues/245 - though that feature might require some loculus TS work eventually - but for now best to have one issue where we can discuss/plan.
