### ISSUE TITLE
[BUG] Getting "Connection problem Please check your internet connection" on search page for Desktop Chrome 130

### ISSUE THREAD

**Issue by corneliusroemer** [loculus-project/loculus#3022]
_Originally posted in https://github.com/pathoplexus/pathoplexus/issues/248 but transferred here after it was reproduced on https://main.loculus.org_
**Describe the bug**
When opening https://pathoplexus.org/west-nile/search? I get a red box saying `Connection problem Please check your internet connection` - but I do have an internet connection and dev console shows no issues loading anything.

It affects all pathogens, but only for Chrome 130 (not other browsers).

The page seems to be mostly unresponsive, only showing server side rendered search results page - almost no interaction works, see screencast:

![2024-10-18 13 52 19](https://github.com/user-attachments/assets/ccfdc3fa-11ce-4937-8799-ef3f310e2e76)

Discovery:
- There's a spinner after "Search returned 6,945 sequences"
- When clicking on any search fields, I get "Loading" and nothing shows up

--> This indicates something is wrong with connection to LAPIS
<img width="917" alt="image" src="https://github.com/user-attachments/assets/9ef6e7ad-08c1-441c-91f6-6a343dc4c595">

- No requests to LAPIS are ever made - this is weird. It really doesn't seem to be a network issue I have, but a bug in the website code, that for some reason only I seem to trigger right now.

@anna-parker and I have found the line of code that triggers the error box:
https://github.com/loculus-project/loculus/blob/025bca84c9204ee6169c8a5ecf9e932ed5f221e8/website/src/components/SearchPage/SearchFullUI.tsx#L304-L305

Upon investigation, reproduction so far only works for me on one exact version of Chrome:

Repro works:
- Chrome 130 on macOS: Version 130.0.6723.59 (Official Build) (arm64) [incognito and non-incognito]

Fail to repro:
- Chrome 131 on macOS (beta)
- Chrome 132 on macOS (canary)
- Chrome mobile (Emma)
- Brave 130: Version 130.0.6723.59 (Official Build) (arm64)
- Chrome 129 mobile Android
- Chrome Version 129.0.6668.103 (Official Build) (arm64) Anya

I can also reproduce on:
- https://staging.ppx.bio
- https://preview-main.ppx.bio
- https://main.loculus.org

**Comment by anna-parker** [comment]
The `isPaused` state is set in this library used by zodiosHook: https://tanstack.com/query/latest/docs/framework/react/reference/useQuery, we have not had any recent changes it checks if your browser is online

**Comment by corneliusroemer** [comment]
Client side error reporting with something like Sentry would really help find out if this just affects one unlucky dev or is actually more widespread: https://github.com/loculus-project/loculus/issues/806

**Comment by corneliusroemer** [comment]
I suppose we can close this as not reproducible/Chrome issue for now - we've now got a better error message in case it happens to others in the future.
