### ISSUE TITLE
Overhaul review page: pagination and better filtering

### ISSUE THREAD

**Issue by theosanderson** [loculus-project/loculus#3031]
As a reviewer I'd like to have a fast and efficient review page. Currently the review page for submitters works in a non-ideal way:

- ~~it makes a big request that gets every sequence satisfying the requirements, which may be thousands leading to OOM https://github.com/loculus-project/loculus/issues/2884 https://github.com/loculus-project/loculus/issues/2881.~~

- it also gets additional data in a lazy-load approach for everything on the page, making a lot of requests per page

- also it allows filtering for errors but does not allow filtering for warnings. User should be able to find any sequences that led to warnings easily https://github.com/loculus-project/loculus/issues/1372

It would be great to overhaul this
- allowing filtering of errors and warnings (independently, or together) [on the server side]
- probably with the backend providing all the data needed to render a single paginated page of the review page in a single request (#1000).

### Other related issues:

- https://github.com/loculus-project/loculus/issues/2561
- https://github.com/loculus-project/loculus/issues/3116
- https://github.com/loculus-project/loculus/issues/3095

## Acceptance criteria

- All relevant data for the review table can be requested from the backend in a single request (requests shouldn't scale up with number of rows)
- The backend doesn't crash, i.e. pagination should also be done at the DB request level
- There is a way to view only sequences with warnings
- All public and dev documentation adapted to new statuses, for example `ripgrep "AWAITING_APPROVAL"` should no longer show results (except for false positives)

**Comment by theosanderson** [comment]
Currently the filtering on errors relies on the fact that `HAS_ERRORS` has its own special `status` state. Warnings on the other hand don't have a status associated with them. A refactor could involve:
1. not changing these statuses
2.  adding a `HAS_WARNINGS_BUT_NOT_ERRORS` statuses 
3. removing the `HAS_ERRORS` status and instead merging `AWAITING_APPROVAL` and `HAS_ERRORS` together, then using different property(s) to monitor whether the sequence has  errors or warnings.

My personal vote would be number 3.

**Comment by theosanderson** [comment]
Addressing this may close https://github.com/loculus-project/loculus/issues/1000 (whether directly or indirectly)

**Comment by theosanderson** [comment]
We may want to consider #2208

**Comment by fhennig** [comment]
related: https://github.com/loculus-project/loculus/issues/3095

**Comment by corneliusroemer** [comment]
Note: I added the following point to the acceptance criteria

> - All public and dev documentation adapted to new statuses, for example `ripgrep "AWAITING_APPROVAL"` should no longer show results (except for false positives)

**Comment by theosanderson** [comment]
The individual-requests thing is a lower priority than the filtering-on-warnings thing. I was connecting them because I thought it might make sense to tackle them together but now we've decided not to do that in one PR I'm open to postponing the multiple-requests thing. It's basically a question of whether it's much easier to do now while it's fresh which might argue in favour of it, or not super different in which case it might make sense to move onto other tasks.

**Comment by fhennig** [comment]
I want to have a look at that, I think it won't take long, and like you said now I'm already kind of in the headspace for it

**Comment by fhennig** [comment]
Filtering for warnings is now supported: https://github.com/loculus-project/loculus/pull/3125

the labels on the review cards metadata now use display names: https://github.com/loculus-project/loculus/issues/3116

These smaller issues were fixed:
- a visual bug with the group selector (https://github.com/loculus-project/loculus/issues/3198)
- the tooltips were showing ‘underneath’ the filter (https://github.com/loculus-project/loculus/issues/1447)
- the discard release buttons now have a confirmation popup (https://github.com/loculus-project/loculus/issues/2566)

We tried to rework the endpoints but it wasn't as easy as we thought so we stopped for now (https://github.com/loculus-project/loculus/pull/3189).

This is it for now, we decided to close this ticket with these changes.

**Comment by corneliusroemer** [comment]
I have been wondering what happened to the slow loading review page problem.

It's confusing that various issues pointing out problems with load times were closed in favor of this issue here but then this issue was closed without that being fixed.

It's of course ok to change plans if it turns out something is harder than expected but we should then reopen issues that weren't fixed.

I'll reopen a few issues that weren't fixed.
