### ISSUE TITLE
Investigate MSW update issue

### ISSUE THREAD

**Issue by fhennig** [loculus-project/loculus#3043]
Previously @corneliusroemer reported an issue that we run into when bumping msw: https://github.com/mswjs/msw/issues/2273

The issue was unrelated to msw, but we still have a problem when bumping it. Needs more investigation.

This only affects the tests, so no real prod issues.

The issue appears in msw 2.4.6

**Comment by fengelniederhammer** [comment]
The title should be `MSW`, shouldn't it?

**Comment by fhennig** [comment]
yes, thanks!
