### ISSUE TITLE
Investigation: Author formatting changes not propagating as expected

### ISSUE THREAD

**Issue by anna-parker** [loculus-project/loculus#3060]
### Summary

Staging is showing a duplication of all versions e.g. a sequence with v1 now has 2 v1s.

### Update: Current understanding

In the sequence entries view (which we use for sending data in get-released-data) we incorrectly join on preprocessing pipeline version instead of using it as a filter - this is an old bug (which we have had since we original set up pipeline version updates)- but I overlooked it and kept it in the code when I updated the view to include external metadata.
This means get-released-data contains multiple versions of data one from each preprocessing pipeline version which we send in get-released-data.

The only thing I still don't fully understand is that SILO somehow keeps this duplication but doesn't have one version from the preprocessing version 1 and another from version 2 but sometimes one from both... odd

### History

We tested rolling the changes in https://github.com/loculus-project/loculus/pull/2986 out to PP staging in the following steps:

1. Update staging loculus version to point to author formatting change
2. Let version bump with ingest
3. Run db change script (in https://github.com/loculus-project/loculus/pull/2986#issuecomment-2422696624 - only changes to modify original data)
4. Add new preprocessing pod with new version
5. Let everything be processed
6. Remove old prepro version

Link to accession used in examples: https://staging.pathoplexus.org/seq/PP_00003PJ.1

The database is in the correct state: 
<img width="1178" alt="image" src="https://github.com/user-attachments/assets/918259f0-69cd-4d0e-a56c-9f66232f7747">

However, on the website every entry is doubled:
<img width="425" alt="image" src="https://github.com/user-attachments/assets/4c0250a3-7a84-49f8-8966-f61e6f8d5d68">

A closer look shows that both v1 entries have authors formatted in the old method - which is a contradiction to the database (all other entries are in the new format):
<img width="1423" alt="image" src="https://github.com/user-attachments/assets/0df51cc9-a54d-43fa-be0b-99ac089b842a">

**Comment by anna-parker** [comment]
Investigation shows that this duplication is also in SILO: 
```
curl -X 'GET' \
  'https://lapis-staging.pathoplexus.org/ebola-sudan/sample/details?accession=PP_00003PJ&limit=100&dataFormat=JSON&downloadAsFile=false' \
  -H 'accept: application/json'
```

**Comment by anna-parker** [comment]
Ok so having an entry for each pipeline version in the view has always been this way:
<img width="647" alt="image" src="https://github.com/user-attachments/assets/de93156a-ee82-4dc5-b57a-0e10aedf57c8">
To only have the results of one pipeline version in the output we would have to not join on the pipeline version but
```
from
    sequence_entries_preprocessed_data
    left join all_external_metadata  on
        all_external_metadata.accession = sequence_entries_preprocessed_data.accession
        and all_external_metadata.version = sequence_entries_preprocessed_data.version
where
	sequence_entries_preprocessed_data.pipeline_version = (select version from current_processing_pipeline);
```

**Comment by anna-parker** [comment]
Just checked and get-released-data has 3/8 entries in the old format and the rest of the entries in the new format - consistent with having 4 entries with preprocessing pipeline version 1 and 4 with preprocessing pipeline version 2.

**Comment by corneliusroemer** [comment]
Thanks for the investigatin! I think I found the issue and fixed it: https://github.com/loculus-project/loculus/pull/2986/commits/e150aa342a205ecd9e5170f69af75d0fe066d935#r1813770918

**Comment by corneliusroemer** [comment]
Fixed it!

There was a weird deadlock with the migration, we should definitely test it once more on staging

<img width="1368" alt="image" src="https://github.com/user-attachments/assets/0526995a-1447-49a1-9e20-cddae9af9640">

**Comment by anna-parker** [comment]
Closing as we think this is fixed with new view
