### ISSUE TITLE
chore: Migrate ESLint 8 to 9

### ISSUE THREAD

**Issue by fhennig** [loculus-project/loculus#3069]
I have disabled the dependabot upgrades for ESLint 9 for now: https://github.com/loculus-project/loculus/pull/3057

A move from 8 to 9 will have to include migrating to the new config format.

I have decided to track this in it's own issue, so we can prioritize doing this. Not sure if it's really that important.

We need to migrate the config file and the automatic [migration tool](https://eslint.org/docs/latest/use/configure/migration-guide#migrate-your-config-file) doesn't work well for `.js` eslintrc files, so it'll be a manual effort.

links:
- https://eslint.org/docs/latest/use/migrate-to-9.0.0
- https://eslint.org/docs/latest/use/configure/migration-guide

### Tasks

- [ ] migrate to the new config format first
- [ ] then bump to the new major version

**Comment by corneliusroemer** [comment]
Thanks! I've tried this before and decided we were blocked until `eslint-plugin-import` supports eslint9. I had a draft PR: https://github.com/loculus-project/loculus/pull/2472/files

Turns out that support has landed now: https://github.com/import-js/eslint-plugin-import/issues/2948 so we're no longer blocked!

**Comment by fhennig** [comment]
I have also tried, here's my draft: https://github.com/loculus-project/loculus/pull/3082

My verdict is that there's still a lot of guesswork. I've spent a few hours on this and I'm still not sure if what I have is correct.

I initially thought that this would be a 'quick' thing, and now it looks like there's more work involved. I'll shelve this for now as it's really not that important at all.
