### ISSUE TITLE
Auth Issues running the webpage locally - unable to talk to LAPIS/SILO

### ISSUE THREAD

**Issue by anna-parker** [loculus-project/loculus#3076]
My standard way of testing new ingest pipelines is to run the webpage, backend, ingest and prepro locally but have the database, keycloak and lapis/silo in docker containers. I have used this set up for the last 6months. 

Today the local website stopped being able to talk to silo - for all organisms there is this long error:
```
{"message":"Network Error","name":"AxiosError","stack":"AxiosError: Network Error\n at XMLHttpRequest.handleError (http://localhost:3000/node_modules/.vite/deps/chunk-XAP7GRWV.js?v=b56f41ed:1623:14)\n at Axios.request (http://localhost:3000/node_modules/.vite/deps/chunk-XAP7GRWV.js?v=b56f41ed:2145:41)\n at async B.request (http://localhost:3000/node_modules/.vite/deps/@zodios_core.js?v=b56f41ed:336:102)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"adapter":["xhr","http","fetch"],"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json"},"baseURL":"http://localhost:8080/h5n1","method":"post","url":"/sample/details","data":"{\"versionStatus\":\"LATEST_VERSION\",\"isRevocation\":\"false\",\"nucleotideMutations\":[],\"aminoAcidMutations\":[],\"nucleotideInsertions\":[],\"aminoAcidInsertions\":[],\"fields\":[\"authorAffiliations\",\"authors\",\"geoLocAdmin1\",\"geoLocCountry\",\"hostNameScientific\",\"ncbiReleaseDate\",\"sampleCollectionDate\",\"accessionVersion\"],\"limit\":100,\"offset\":0,\"orderBy\":[{\"field\":\"sampleCollectionDate\",\"type\":\"descending\"}]}","params":{}},"code":"ERR_NETWORK"}
```
I see no errors in silo or lapis, just 200 requests. I see that according to the database all my sequences have been uploaded and have finished processing successfully. 

However I see some errors in the keycloak logs (I removed USERID and IPADDRESS before posting here): 
```
2024-10-25 08:40:17,428 INFO  [org.keycloak.services] (main) KC-SERVICES0009: Added user 'admin' to realm 'master'
2024-10-25 08:55:11,171 WARN  [org.keycloak.events] (executor-thread-3) type="CODE_TO_TOKEN_ERROR", realmId="bd61a1f2-b110-4acf-8ef4-c9cbde0d3aae", clientId="backend-client", userId=USERID, ipAddress=IPADDRESS, error="invalid_code", grant_type="authorization_code", code_id="da6c612d-efb6-4182-a3e8-892cd547edeb", client_auth_method="client-secret"
```

**Comment by anna-parker** [comment]
Solved! I had another service running on localhost:8080 - I stopped it and now the backend is running on the correct port

**Comment by gordonkoehn** [comment]
Hi @anna-parker,

I am getting a similar error for my testing instance deployed at "[https://wise-seqs.loculus.org/test](https://wise-seqs.loculus.org/test)" (default credentials).

It shows me `"message":"Network Error","name":"AxiosError","stack":"AxiosError: ` on the "Browse/Search" page. See below.

This instance has sequences submitted, and I can programmatically download the entries of submitted sequences. 

The webpage just runs into the error when I want to display submitted sequences.

<img width="1090" alt="Image" src="https://github.com/user-attachments/assets/36b8cd56-ea87-4650-b11d-3310af19d78a" />

Would you know if this may be related? Shall I make a new issue elsewhere?

**Comment by anna-parker** [comment]
Hey @gordonkoehn this might be a different issue - can you see the LAPIS logs and/or make a curl request to LAPIS?
