### ISSUE TITLE
Ingest: Explore submitting updated metadata as biosample updates to ENA

### ISSUE THREAD

**Issue by corneliusroemer** [loculus-project/loculus#3086]
We should test how well updating of metadata works via updated biosamples, without doing automation/pipeline development yet

**Comment by anna-parker** [comment]
I will attempt to revise the taxonId for https://pathoplexus.org/seq/PP_000RGTE.1 and https://pathoplexus.org/seq/PP_000RGSG.1.

**Comment by anna-parker** [comment]
Updates are successful on dev, but I see no results on the page 
```
curl -u "$username:$password" -F 'SUBMISSION=@sample/submission.xml' -F 'SAMPLE=@sample/sample.xml' https://wwwdev.ebi.ac.uk/ena/submit/report > results/output.txt
```

**Comment by anna-parker** [comment]
It could be just the dev site being down, I tried now to update the page using the browser and I get an error: 
<img width="1018" alt="image" src="https://github.com/user-attachments/assets/17aca06a-4998-4348-93f1-67430a2160e9">

**Comment by anna-parker** [comment]
Ok I tried on the main site as well and programmatic submission again resulted in a successful curl request but no changes on the page - however I was able to just edit the page and here the update was successful

**Comment by anna-parker** [comment]
Update: I do find an error when I submit updates programmatically on dev: 
```
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="receipt.xsl"?>
<RECEIPT receiptDate="2024-11-05T09:54:05.497Z" submissionFile="submission.xml" success="false">
     <SAMPLE alias="PP_000RGSG:west-nile:Pathoplexus" status="PUBLIC"/>
     <SUBMISSION alias="SUBMISSION-05-11-2024-09:54:05:240"/>
     <MESSAGES>
          <ERROR>Failed to submit samples to BioSamples</ERROR>
          <ERROR>Failed to submit samples to BioSamples</ERROR>
          <ERROR>An exception occurred: java.lang.RuntimeException: Failed to submit all samples to BioSamples</ERROR>
          <INFO>This submission is a TEST submission and will be discarded within 24 hours</INFO>
     </MESSAGES>
     <ACTIONS>MODIFY</ACTIONS>
</RECEIPT>
```

**Comment by anna-parker** [comment]
It worked on prod!!!!

**Comment by corneliusroemer** [comment]
One is mostly updated (except for Organism and Scientific Name, at least on the biosample page): https://www.ebi.ac.uk/ena/browser/view/SAMEA116100917
The other one is not yet changed: https://www.ebi.ac.uk/ena/browser/view/SAMEA116120071

Curiously, this one shows ENA first public Year 1000: 
<img width="652" alt="image" src="https://github.com/user-attachments/assets/32cab2fc-1568-4cce-b032-f32fb4776d78">

**Comment by anna-parker** [comment]
Both have now updated the lat, long values on ENA however taxon has remained the same and changes are not visible on NIH.

**Comment by anna-parker** [comment]
Yay! All the updates have propagated to ENA and NIH!
