### ISSUE TITLE
Modify how the backend handles "new metadata" fields e.g. when the config changes

### ISSUE THREAD

**Issue by anna-parker** [loculus-project/loculus#3106]
Adding new metadata fields to the values.yaml causes an issue because metadata fields that was processed by prepro prior to the addition of the field does not contain the new field. The data is stored in the database and then sent to LAPIS/SILO without processing. With the new config they expect the new metadata field that does not exist.

The backend needs to be prepared for this case. It's designed to validate that processed data can be imported by SILO. So it should also catch the case when the config changes:

* The backend could process data it sends to LAPIS/SILO and add in null fields, or LAPIS/SILO prepro could do this apon data retrieval. Such a change would mean the backend would not need to store fields with null - this could be removed from prepro and save on storage cost.
* It could throw an error that we handle in the SILO import job - indicating that `/get-released-data` needs to wait for reprocessing, this would require us to wait for the preprocessing pipeline updates (when we bump the version) to rollout.

_Originally posted by @fengelniederhammer and @anna-parker in https://github.com/loculus-project/loculus/issues/2945#issuecomment-2396043606_

**Comment by anna-parker** [comment]
I am marking this as high priority as until we fix this we cannot add new metadata fields: e.g. https://github.com/loculus-project/loculus/issues/2945 to the values.yaml without lapis/silo erroring and a high probability of pathoplexus not being available.

**Comment by corneliusroemer** [comment]
I thought I already had an issue and solution for this: simply store only non-null fields and treat everything as null by default, so rehydrate with nulls based on whatever schema one has when streaming to get released data

**Comment by corneliusroemer** [comment]
We keep reinventing the wheel a little layers of duplicated issues, not a big problem, makes it easy to find it when scanning/searching.

But this was the original proposal to not store nulls which would also work around the "new fields pop up" problem: https://github.com/loculus-project/loculus/issues/2793

**Comment by corneliusroemer** [comment]
Can we agree to do the null thing, I thought we'd already agreed, at least tacitly in 2793, are there objections? If not we can close this here and just say we do 2793 with high prio 😀

**Comment by anna-parker** [comment]
Oh Im sorry I couldn't find https://github.com/loculus-project/loculus/issues/2793! Totally agree - lets go with that one - happy to close this and move forward with the `null` values
