### ISSUE TITLE
Hide "Help" button in search panel by default

### ISSUE THREAD

**Issue by chaoran-chen** [loculus-project/loculus#3140]
The search panel has a "Help" button on top:

![image](https://github.com/user-attachments/assets/661ddc3d-e27f-43e9-9537-3458a031bafd)

This links to `/docs/how-to/search-sequences-website` which has content on Pathoplexus (see [here](https://pathoplexus.org/docs/how-to/search-sequences-website)) but not in the base Loculus, so it should be configurable and be hidden by default.

**Comment by theosanderson** [comment]
Or one could add some basic search instructions there

**Comment by chaoran-chen** [comment]
/docs/how-to/search-sequences-website would be a strange URL though for Loculus. Instead, one cold by default link to docs.loculus.org and make it configurable.

**Comment by theosanderson** [comment]
It doesn't seem a crazy URL to me :)

**Comment by chaoran-chen** [comment]
There wouldn't be anything at /docs or /docs/how-to and the Docs button in the footer points to docs.loculus.org, so to me, it seems much more natural to direct to docs.loculus.org again. The alternative would be that we move the complete user docs from docs.loculus.org to the platform but that would be a major change.

**Comment by theosanderson** [comment]
Cool, it's not something I feel strongly about – it just seemed an easy fix. It's kind of useful to have some pages in Loculus to be able to test the docs features but we don't have to have them linked to.
