### ISSUE TITLE
Make Welcome message configurable

### ISSUE THREAD

**Issue by chaoran-chen** [loculus-project/loculus#3161]
I think that it would be nice if we can make the Welcome message on the landing page configurable. At the moment, it always says

> Welcome to {website name}, a system for sharing pathogen genome data.

Instead, I'd suggest adding a config like `welcomeMessageHTML` that an admin can set to overwrite this message.

**Comment by fhennig** [comment]
Hmm, I can see it being useful in principle. Should it be directly in HTML (as the suffix on your suggested config option suggests)? Would it still be possible to use `website name` as a template variable somehow?

**Comment by chaoran-chen** [comment]
HTML would be most flexible and we already have a few places where people can insert HTML through the config such as `additionalHeadHTML` and I think also for the yellow top banner (that shows up for some instances).

> Would it still be possible to use `website name` as a template variable somehow?

By default, if the config is not set / set to `null`, I'd say that we will still display the text as now. This will be done directly in the website code, meaning that the new config will be considered optional for the website application. If the admin defines a message, I don't know whether they can do some templating through Helm magic but I wouldn't implement a feature specifically.

**Comment by corneliusroemer** [comment]
To be explicit, I think you're talking about this, correct?

<img width="1475" alt="image" src="https://github.com/user-attachments/assets/53dd0235-58fa-4426-848d-3e7c9aee60c0">

**Comment by chaoran-chen** [comment]
Yes, exactly! :)
