### ISSUE TITLE
Review page filters show above group dropdown

### ISSUE THREAD

**Issue by corneliusroemer** [loculus-project/loculus#3198]
The group dropdown is behind the new filters, some z-score thing:

<img width="600" alt="Google Chrome Beta 2024-11-11 19 17 25" src="https://github.com/user-attachments/assets/87a9f64c-9199-4594-9f5b-aced3f9cd4ea">

![2024-11-11 19 17 34](https://github.com/user-attachments/assets/b73768ba-2691-4898-8d0f-b03396d12514)

_Originally posted by @corneliusroemer in https://github.com/loculus-project/loculus/issues/3125#issuecomment-2468773891_

Low prio because only relevant for curators (mostly).

**Comment by chaoran-chen** [comment]
This is an old issue: #1447

**Comment by corneliusroemer** [comment]
Ah good spot that it's _potentially_ the same issue, it shows slightly differently here but yeah, likely the same (let's hope). I think it'd be good to keep this open to double check it's resolved by the eventual fix to #1447?
