### ISSUE TITLE
Include pipeline version in 'get-released-sequences' as a metadata field

### ISSUE THREAD

**Issue by corneliusroemer** [loculus-project/loculus#3209]
@fengelniederhammer raised a good point that we don't currently emit the pipeline version used to process sequences at all. This isn't great, the only way to work around this right now is to query the db.

We should somehow include the pipeline version in the response of `get-released-sequences`.

As it's NDJSON we can't put it in an info top-level-key unfortunately.

So we have options to:
- include in HTTP header
- emit as metadata field

We should probably just put it as a metadata field, that would also allow us in the future to use different pipeline versions for different organisms, something we've wanted to enable in the future to not have to reprocess everything if a single organism's Nextclade dataset is updated.

Some background discussion: https://loculus.slack.com/archives/C05G172HL6L/p1731500439841509

_______

Acceptance criteria:

- The `get-released-sequences` endpoint contains a `pipelineVersion` field for each item with the pipeline version (which will be the same for all sequences)
- The kubernetes config is adjusted to add this field to `kubernetes/loculus/templates/_common-metadata.tpl`

**Comment by theosanderson** [comment]
I support having it as a metadata field

**Comment by theosanderson** [comment]
But in the Slack discussion Fabian wrote:

> Is there a way to see which pipelineVersion was used to process a sequence entry (without looking into the DB directly)?

(And I agree this would be valuable)

For this I think we would need it to be a field? Or would need to adapt LAPIS to return this data? Or maybe it already has a metadata concept for the whole dataset?

**Comment by chaoran-chen** [comment]
LAPIS has one mechanism for declaring the version of its output and that's the `data version` that is provided in each response. So, a non-redundant way would be to create a separate mapping of the data version to the pipeline version. For now, if we want to get the value from LAPIS, then adding it as a field is indeed the easiest.

**Comment by theosanderson** [comment]
I added some acceptance criteria to the issue based on the discussion above - please shout with any disagreements or comments

**Comment by fhennig** [comment]
How I'd go about doing it:
- Update the `sequence_entries_view` to also include the `pipeline_version` (i.e. requires a DB migration)
- Fetch the `pipelineVersion` in `SubmissionDatabaseService.streamReleasedSubmissions`. This also means adding the `pipeline_version` to the `RawProcessedData` type.
- Emit the field as a new `ProcessedData.metadata` field.
- The `_common-metadata.tpl` is adjusted to add the `pipelineVersion` field as metadata to all organisms by default.
