### ISSUE TITLE
Unable to curate sequences in Loculus

### ISSUE THREAD

**Issue by anna-parker** [loculus-project/loculus#3224]
When trying to curate sequences I am unable to do so because the enums are not recognized:
![image](https://github.com/user-attachments/assets/ff3580f9-7ad2-495f-9644-f1425933117d)

It looks like it is linked to this change: https://github.com/loculus-project/loculus/pull/3125

**Comment by corneliusroemer** [comment]
Can reproduce on main:
1. login as superuser
2. Click "revise" on any released sequence

![2024-11-18 16 17 44](https://github.com/user-attachments/assets/12612c16-efa0-49cc-b1b7-42e2b1afa01f)

**Comment by theosanderson** [comment]
This line was inserted in that PR but is not required - we can delete it: https://github.com/loculus-project/loculus/commit/e83bce308f85f8c89ce705e81856db3a9b3476c1#diff-02b6f15e76cb770bb98c143bdc192f5095944a72ebb388db9041ad4d92ebd032R951-R952
