### ISSUE TITLE
Revoked sequences always have original submitter of the revoked version as the submitter, rather than the revoker

### ISSUE THREAD

**Issue by corneliusroemer** [loculus-project/loculus#3244]
Just noticed that when I revoke an INSDC ingested sequence as a curator on staging ingest seems to auto approve the revocation. That's probably not what we want.

**Comment by anna-parker** [comment]
Just checked the staging DB and it looks like sequences that we revoked are listed as being revoked by he `insdc_ingest_user`: 
![image](https://github.com/user-attachments/assets/d1c2185d-b4fa-4bad-b3ba-fd8e8c259390)

**Comment by corneliusroemer** [comment]
Interesting, that looks like a bug then! Revocation seems to have "submitter" set to the wrong account.

**Comment by theosanderson** [comment]
👍 I guess here it is just cloning the old submitter:
                SequenceEntriesTable.submitterColumn,
                
                https://github.com/loculus-project/loculus/blob/a6b3bb77e7a61d49191eac042c8a541b6c35f667/backend/src/main/kotlin/org/loculus/backend/service/submission/SubmissionDatabaseService.kt#L775
