### ISSUE TITLE
Submission portal takes multiple seconds to load if there are 10k sequences to review 

### ISSUE THREAD

**Issue by corneliusroemer** [loculus-project/loculus#3269]
We no longer have OOM (at least for 10k sequences) as mentioned here: https://github.com/loculus-project/loculus/issues/2881#issue-2550791971 but load times are still unacceptably long if there are thousands of sequences to review/approve (e.g. curators).

West Nile shows blank screen to superusers for 10+ seconds.

This wasn't fixed in #3031 

The issue isn't that there are many request made. It's that the website server seems to block, waiting for stuff.

Maybe mitigating the stall is as simple as disabling SSR of this page?

It's particularly the `/[organism]/submission/[groupid]` page that's slow. It's blocking on getSequences on the server side. 

There are a number of options here for speed up:
- We could refactor it to get the count of sequences on the client side
- Speed up getSequences
- ...

![2024-11-23 05 42 43](https://github.com/user-attachments/assets/ec943b39-8d89-4969-9ec4-b20b68b44d90)

Relevant code is here:

https://github.com/loculus-project/loculus/blob/531c2bc3055ab344ad11035dfd93c20709692453/website/src/pages/%5Borganism%5D/submission/%5BgroupId%5D/index.astro#L19-L44

**Comment by corneliusroemer** [comment]
Actually Fabian already made an issue for this way back: https://github.com/loculus-project/loculus/issues/1612

**Comment by chaoran-chen** [comment]
Should we then close this ticket and use #1612? I renamed the title of #1612 to be more clear about the impact of the slow endpoint.

**Comment by corneliusroemer** [comment]
These are slightly different issues: Fabian talks about the backend endpoint and this here is about slowness of the website. They might be solved in one go because they are due to same root cause or they might be fixed independently.
