### ISSUE TITLE
We can accept at most ~60k sequences per submission: should be documented on submission page

### ISSUE THREAD

**Issue by corneliusroemer** [loculus-project/loculus#3281]
While it's unlikely anyone will submit more than 60k sequences in one go, it'd be good to document this.

I tried to upload 100k dummy sequences on main and it caused endless loading followed by an error:

```
Internal Server Error: org.postgresql.util.PSQLException: PreparedStatement can have at most 65,535 parameters. Please consider using arrays, or splitting the query in several ones, or using COPY. Given query has 100,000 parameters
```

We should probably catch this earlier before we get an SQL exception.

<img width="1841" alt="Google Chrome 2024-11-23 09 24 57" src="https://github.com/user-attachments/assets/c2fca662-32ac-4baa-a06a-6a18b09620e5">

**Comment by chaoran-chen** [comment]
This is long known ;) #1613

**Comment by corneliusroemer** [comment]
So long it should have been fixed long ago 😁
