### ISSUE TITLE
Submission template: have a subset of fields in template

### ISSUE THREAD

**Issue by theosanderson** [loculus-project/loculus#3331]
We have an overwhelming number of fields. We should make the default template only have a subset of fields, and in a specific order that is useful. People can always add more fields based on the docs.

### Acceptance criteria

The values.yaml `schema` object has a new optional property, that looks like this:

```
metadataTemplate: [sampleCollectionDate, geoLocCountry]
```

It has a list of field names, which are used to construct the metadata template in place of the full list if set. (submissionId is always added at the front to whatever is in the list).

**Comment by theosanderson** [comment]
I think I am currently imagining this just as a list of values in the helm template.

**Comment by rneher** [comment]
Agreed. the current template is pretty unusable. it should 
 - list the required fields first
 - common optional fields in a sensible grouping.

**Comment by emmahodcroft** [comment]
I wonder if we could also just have a mouseover on the submission page that lists the required fields, too - there aren't that many and it could make this very clear?

**Comment by emmahodcroft** [comment]
Theo just to be clear on your acceptance criteria, are you saying that only required fields would be in the YAML or that it would just be some subset of those we think may be most useful?

**Comment by theosanderson** [comment]
The fields listed would be the ones that would appear in the template. Whether one puts just the required fields in the template or a broader selection would be up to the maintainer of the instance.

**Comment by chaoran-chen** [comment]
Should we then also include in the config whether a field is required and/or recommended? This can then be used on the one hand to generate documentation and on the other hand we can also e.g. offer a template with only required/recommended fields and another one with all fields?

**Comment by theosanderson** [comment]
I think it's also important to be able to specify the order that fields will appear in the template, and I I personally don't think the template needs to be tied to recommended fields, just whatever we think is most useful (it might be somewhere between recommended and "full" by default I suspect).

**Comment by theosanderson** [comment]
(the order point there is probably the more significant one for me)

**Comment by rneher** [comment]
@fhennig to me that seems like a fairly simple change that would a big usability win for users. Do you have enough specifics to pick this up?

**Comment by theosanderson** [comment]
I don't think that's quite right. This is just about the template that users can download on the Submit page. So it doesn't have those common metadata items, and it only affects the website. And it only affects that one route on the website.

**Comment by fhennig** [comment]
Ok then I didn't get it I think, oops! I'll just message you on slack

**Comment by fhennig** [comment]
Ok @theosanderson just sent me this picture:
![image](https://github.com/user-attachments/assets/5c592959-dc1f-49b3-9428-10f948ee3f6a)
Now I know what is actually meant by template. Yeah I think now I know what to do!
