### ISSUE TITLE
Updating data use terms doesn't trigger an update of SILO

### ISSUE THREAD

**Issue by fhennig** [loculus-project/loculus#3354]
I have released some sequences on main.loculus.org and the update didn't show up even after a few minutes.

I suspect that we require

something like `SELECT create_update_trigger_for_table('user_groups_table');` but for `data_use_terms_table`.

The https://github.com/loculus-project/loculus/blob/8a22aa84649ab2499edcc8c0b58eab7b15ce8391/backend/docs/db/schema.sql seems to confirm that a trigger is indeed not set for this table.

**Comment by corneliusroemer** [comment]
Good point, this might indeed be something @anna-parker and I forgot when doing the etag thing.

**Comment by fhennig** [comment]
Thanks for the quick fix @corneliusroemer 🤩
