### ISSUE TITLE
Send full geoloc information (including division 2 and city) via biosample (and possibly also main location string)

### ISSUE THREAD

**Issue by corneliusroemer** [loculus-project/loculus#3435]
I've noticed we don't send all the geo location information we have to ENA. Division 2 and City are lost it seems:

<img width="941" alt="Google Chrome 2024-12-12 16 11 03" src="https://github.com/user-attachments/assets/c2153625-3113-45c5-9af2-c01446531af5" />

info we have:
<img width="468" alt="Google Chrome 2024-12-12 16 13 53" src="https://github.com/user-attachments/assets/5d7c38f5-928e-49d4-a896-0e95ff36749d" />

We should probably somehow serialize all hierarchical information we have into the location string, something like `Connecticut, Hartford, West Hartford`.

I fear biosample has no way to split things up things other than with comma, so that's what we'll have to do.

```
Qualifier       /geo_loc_name=
Definition      locality of isolation of the sequenced sample indicated in
                terms of political names for nations, oceans or seas, followed
                by regions and localities
Value format    "<geo_loc_name>[:<region>][, <locality>]" where
                geographic location name (geo_loc_name) is any value from the controlled vocabulary at
                http://www.insdc.org/country.html
Example         /geo_loc_name="Canada:Vancouver"
                /geo_loc_name="France:Cote d'Azur, Antibes"
                /geo_loc_name="Atlantic Ocean:Charlie Gibbs Fracture Zone"
Comment         Intended to provide a reference to the site where the source
                organism was isolated or sampled. Regions and localities should
                be indicated where possible. Note that the physical geography of
                the isolation or sampling site should be represented in
                /isolation_source.
```

from https://www.ncbi.nlm.nih.gov/genbank/collab/country/

**Comment by anna-parker** [comment]
As we do send this information now - I will close this - I have created a separate ticket for revising the country information: https://github.com/loculus-project/loculus/issues/3437
