### ISSUE TITLE
(Optional?) changelog / reason with revision/revocation

### ISSUE THREAD

**Issue by theosanderson** [loculus-project/loculus#640]
@emmahodcroft flagged that we should have the option (IMO it might be complex to enforce this due to the fact that people might do this through an API) for users to with a revocation or a revision note why the change was made. I think this is an important feature. It would be a free-text field of a few hundred characters. E.g. "We resequenced this and found that the previous sequence was affected by contamination".

**Comment by chaoran-chen** [comment]
As @anna-parker said, it is now possible to have a change log, so I think this issue is done. If someone sees a missing feature, it would be great to have a more specific issue.
