### ISSUE TITLE
Version comparison

### ISSUE THREAD

**Issue by chaoran-chen** [loculus-project/loculus#69]
It would be great to be able to compare two versions (to be implemented in #68) of a sequence/metadata and see the differences.

(It's a nice-to-have feature and doesn't have a high priority. I'll add it to the MVP milestone for now but if it's too complicated, we might not do it.)

**Comment by corneliusroemer** [comment]
Closed in favour of https://github.com/loculus-project/loculus/issues/2803 because that issue contains a description from current perspective (rather than knew from a year ago)
