### ISSUE TITLE
Pango lineage field intersperses "*" when typing

### ISSUE THREAD

**Issue by theosanderson** [loculus-project/loculus#964]
Try typing multiple chars into the pangoLineage field https://main.loculus.org/dummy-organism/search:

it appears like this:

![image](https://github.com/loculus-project/loculus/assets/19732295/06017cfd-30ce-48c9-bbf4-92bb245766fd)

**Comment by theosanderson** [comment]
We no longer have a pangoLineage field atm

**Comment by corneliusroemer** [comment]
Hmm, are you sure the field is purged from the config entirely?

I would like a lineage search (for West Nile) very soon, that uses wildcards. But I guess that would be a different field? I should make a separate issue.
